name: Deploy to Render
on: 
  push:
    tags:
      - '*'

jobs:
  build-node:
    name: Build and run Node project
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    container: node:20
    steps:
      - uses: actions/checkout@v3
        name: Check out code from Github

      - run: npm install
        name: Install NPM packages

  deploy:
    name: Deploy to Render
    needs: [build-node]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
